In [5]:
dat <- read.csv('D:/samsung_ai/test/train_dat.csv')
attach(dat)

In [10]:
substr(dat$date[1], 1, 8)

[1] "20170630"

In [11]:
head(dat)

  year date       num day_night day num_death 사상자수 중상자수 경상자수
1 2017 2017063023 14  야간      금  1         1        0        0
2 2017 2017063021 45  야간      금  1         4        2        1
3 2017 2017063021 50  야간      금  1         1        0        0
4 2017 2017063019 10  야간      금  1         1        0        0
5 2017 2017063017  2  주간      금  1         2        1        0
6 2017 2017063010 59  주간      금  1         1        0        0
  부상신고자수 ... 도로형태_대분류 도로형태   당사자종별_1당_대분류
1 0            ... 단일로          기타단일로 승용차
2 0            ... 단일로          기타단일로 승용차
3 0            ... 단일로          기타단일로 승용차
4 0            ... 교차로          교차로부근 승용차
5 0            ... 단일로          교량위     이륜차
6 0            ... 단일로          기타단일로 이륜차
  당사자종별_1당 당사자종별_2당_대분류 당사자종별_2당 발생위치X_UTMK
1 승용차         보행자                보행자          967633
2 승용차         승용차                승용차          966456
3 승용차         보행자                보행자          900057
4 승용차         이륜차                이륜차         1095230
5 이륜차         화물차                화물차          947576
6 이륜차         승용차                승용차          939085
  발생위치Y_UTMK 경도     위도
1 1937456        127.1341 37.43570
2 1696405        127.1312 35.26253
3 1865697        126.3799 36.78414
4 1764891        128.5549 35.87597
5 1946355        126.9068 37.51499
6 1681915        126.8314 35.13059