In [2]:
import pandas as pd

In [3]:
from math import sin, cos, sqrt, atan2, radians

In [4]:
data1 = pd.read_csv("C:/Users/renz/Downloads/Query_Executor_out.csv")
data2 = pd.read_csv("C:/Users/renz/Downloads/PORT4.csv")

In [7]:
L2 = []
for i,j,k in zip(data1['MMSI2'], data1['LAT'], data1['LON']):
    L1 = []
    for l1, l2 in zip(data2['LATITUDE'], data2['LONGITUDE']):
        R = 6373.0 
        lat1 = radians(j) 
        lon1 = radians(k) 
        lat2 = radians(l1) 
        lon2 = radians(l2) 
        dlon = lon2 - lon1 
        dlat = lat2 - lat1 
        a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2 
        c = 2 * atan2(sqrt(a), sqrt(1 - a)) 
        distance = R * c
        L1.append(distance)
    L2.append(min(L1))

In [8]:
data1['distance'] = L2

In [9]:
data_5km = list(data1[data1['distance'] <= 5]['MMSI2'].value_counts()[data1[data1['distance'] <= 5]['MMSI2'].value_counts() == 2].index)

In [10]:
data3 = data1[data1['MMSI2'].apply(lambda x: x in data_5km)]

In [12]:
data3

,ETA,ETA2,MMSI,LAT,LON,SPEED,DATE_DIFF,CASE_DIFF,CUM_SUM,MMSI2,NROW,NROW_MAX,distance
6,2018-03-23 00:03:07,2018-03-21 20:34:19,209087000,30.6202,122.0576,10.0,2.0,1,10,209087000_10,1,12773,1.341109
7,2018-06-01 23:26:02,2018-06-01 23:21:40,209087000,25.1497,121.7522,1.0,0.0,0,10,209087000_10,12773,12773,0.515074
50,2018-04-25 18:37:39,2018-04-23 22:41:42,209540000,35.6061,139.7796,5.0,2.0,1,49,209540000_49,1,1133,4.311670
51,2018-05-15 00:06:00,2018-05-14 23:51:49,209540000,35.5715,139.8419,1.0,1.0,0,49,209540000_49,1133,1133,4.674049
74,2018-04-08 20:29:13,2018-04-06 00:48:54,209597000,35.4015,139.6799,2.0,2.0,1,66,209597000_66,1,2041,1.869351
75,2018-04-26 22:27:02,2018-04-26 22:12:01,209597000,38.9722,117.7869,2.0,0.0,0,66,209597000_66,2041,2041,0.442331
98,2018-03-09 18:37:22,2018-03-07 02:17:58,209828000,-6.7447,146.9861,3.0,2.0,1,29,209828000_29,1,1776,1.223792
99,2018-04-02 04:25:47,2018-04-02 04:21:35,209828000,-6.7333,146.9764,1.0,0.0,0,29,209828000_29,1776,1776,2.388674
180,2017-07-17 05:57:29,2017-07-15 13:19:34,210242000,33.7686,-118.2309,3.0,2.0,1,31,210242000_31,1,15984,2.157807
181,2017-09-02 13:48:02,2017-09-02 13:46:19,210242000,33.7686,-118.2322,1.0,0.0,0,31,210242000_31,15984,15984,2.244697
234,2017-07-21 01:41:14,2017-07-19 19:28:56,210562000,19.0602,-104.3067,7.0,2.0,1,62,210562000_62,1,1349,2.524361
235,2017-07-30 18:13:39,2017-07-30 18:05:36,210562000,-20.2033,-70.1549,2.0,0.0,0,62,210562000_62,1349,1349,0.513137
304,2016-07-02 17:47:51,2016-06-30 11:07:39,210905000,12.4804,-87.1952,8.0,2.0,1,24,210905000_24,1,1745,2.499255
305,2016-07-15 06:00:46,2016-07-15 05:56:42,210905000,9.8988,-84.7546,12.0,0.0,0,24,210905000_24,1745,1745,4.051249
356,2016-01-17 15:13:40,2016-01-14 14:01:47,211377300,35.0768,128.7881,1.0,3.0,1,13,211377300_13,1,2236,1.601377
357,2016-01-30 11:42:57,2016-01-30 11:42:05,211377300,47.5931,-122.3483,3.0,0.0,0,13,211377300_13,2236,2236,3.348992
410,2017-09-12 00:37:07,2017-09-10 21:24:40,211782000,49.2890,-123.0928,2.0,2.0,1,52,211782000_52,1,3549,3.610472
411,2017-10-22 22:13:46,2017-10-22 21:39:17,211782000,54.2972,-130.3637,1.0,0.0,0,52,211782000_52,3549,3549,3.236674
412,2017-10-25 06:41:06,2017-10-22 22:13:46,211782000,54.2855,-130.3633,1.0,3.0,1,53,211782000_53,1,1386,3.947325
413,2017-11-06 00:51:27,2017-11-06 00:41:51,211782000,35.0756,128.7982,2.0,0.0,0,53,211782000_53,1386,1386,1.125779
468,2017-05-21 00:14:27,2017-05-19 07:43:22,212185000,10.0033,-83.0780,1.0,2.0,1,20,212185000_20,1,3268,0.686863
469,2017-06-29 22:38:21,2017-06-29 22:22:10,212185000,10.0138,-83.0823,4.0,0.0,0,20,212185000_20,3268,3268,1.538875
470,2016-03-21 20:30:54,2016-03-19 18:50:45,212185000,19.2100,-96.1338,1.0,2.0,1,4,212185000_4,1,3579,1.296372
471,2016-05-05 21:02:26,2016-05-05 21:00:26,212185000,10.0336,-83.0882,6.0,0.0,0,4,212185000_4,3579,3579,3.775665
472,2016-02-21 17:00:31,2016-02-19 04:39:42,212232000,43.0889,131.8689,3.0,2.0,1,20,212232000_20,1,1979,2.709847
473,2016-03-30 17:46:15,2016-03-30 17:30:44,212232000,43.0905,131.8711,1.0,0.0,0,20,212232000_20,1979,1979,2.549018
496,2015-11-16 01:47:14,2015-11-12 12:47:58,212347000,33.7267,-118.2601,2.0,4.0,1,2,212347000_2,1,3104,1.569665
497,2015-12-09 03:25:24,2015-12-09 03:25:08,212347000,31.3768,121.5775,1.0,0.0,0,2,212347000_2,3104,3104,3.723210
534,2018-08-10 05:41:17,2018-08-08 07:31:39,212355000,43.0684,131.8761,1.0,2.0,1,73,212355000_73,1,1286,2.997334
535,2018-08-21 23:37:30,2018-08-21 23:25:02,212355000,43.0879,131.8664,1.0,0.0,0,73,212355000_73,1286,1286,2.908552
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122580,2018-01-08 12:34:31,2018-01-06 22:51:36,636091912,33.7693,-118.2261,2.0,2.0,1,36,636091912_36,1,20768,1.933111
122581,2018-02-24 14:33:04,2018-02-24 14:33:02,636091912,33.7676,-118.2355,1.0,0.0,0,36,636091912_36,20768,20768,2.411152
122644,2016-05-01 10:31:09,2016-04-27 22:23:19,636092079,33.7659,-118.2741,1.0,4.0,1,14,636092079_14,1,3889,2.978766
122645,2016-06-01 23:02:58,2016-06-01 22:52:13,636092079,33.7422,-118.2008,3.0,0.0,0,14,636092079_14,3889,3889,1.890421
122648,2017-02-09 13:06:58,2017-02-07 21:59:03,636092079,37.8116,-122.3271,2.0,2.0,1,32,636092079_32,1,4406,3.890220
122649,2017-03-09 13:12:22,2017-03-09 13:04:50,636092079,33.7434,-118.1959,1.0,0.0,0,32,636092079_32,4406,4406,2.134059
122650,2017-07-15 15:28:10,2017-07-13 20:10:02,636092079,-37.8491,144.9052,9.0,2.0,1,43,636092079_43,1,5232,3.022504
122651,2017-08-26 19:45:30,2017-08-26 19:40:38,636092079,-37.8748,144.9281,10.0,0.0,0,43,636092079_43,5232,5232,4.082071
122652,2017-08-28 03:32:35,2017-08-26 19:45:30,636092079,-37.8653,144.9218,9.0,2.0,1,44,636092079_44,1,3685,3.238593
122653,2017-09-15 07:31:07,2017-09-15 07:12:39,636092079,13.0673,100.8951,1.0,0.0,0,44,636092079_44,3685,3685,0.957030
122654,2017-11-26 00:22:56,2017-11-24 02:37:54,636092079,-37.8502,144.9065,8.0,2.0,1,50,636092079_50,1,2754,2.967422
122655,2017-12-08 17:14:54,2017-12-08 16:40:36,636092079,13.0642,100.8883,4.0,0.0,0,50,636092079_50,2754,2754,0.930126
122684,2017-09-03 08:16:07,2017-09-01 09:44:42,636092161,-18.4730,-70.3272,1.0,2.0,1,51,636092161_51,1,2979,1.600949
122685,2017-09-21 17:07:50,2017-09-21 17:04:11,636092161,-37.0339,-73.1557,2.0,0.0,0,51,636092161_51,2979,2979,0.966726
122828,2017-09-27 03:03:21,2017-09-25 09:32:59,636092432,-33.0320,-71.6254,1.0,2.0,1,38,636092432_38,1,16704,1.117623
122829,2017-12-04 09:40:12,2017-12-04 09:34:34,636092432,-33.0327,-71.6259,1.0,0.0,0,38,636092432_38,16704,16704,1.149642
122842,2017-02-10 05:17:17,2017-02-08 20:19:28,636092476,2.9504,101.3031,1.0,2.0,1,66,636092476_66,1,1276,0.347218
122843,2017-02-24 01:58:20,2017-02-24 01:29:38,636092476,-6.7502,146.9978,3.0,0.0,0,66,636092476_66,1276,1276,1.024628
122856,2016-11-07 02:08:28,2016-11-05 04:07:56,636092489,33.7686,-118.2309,2.0,2.0,1,21,636092489_21,1,10061,2.157807
122857,2016-11-26 19:49:05,2016-11-26 19:25:38,636092489,-37.8697,144.9249,9.0,0.0,0,21,636092489_21,10061,10061,3.600038
122858,2017-07-07 10:16:51,2017-07-05 22:33:42,636092489,37.7944,-122.3090,1.0,2.0,1,34,636092489_34,1,9142,2.022563
122859,2017-07-30 13:15:06,2017-07-30 13:14:26,636092489,-37.8505,144.9067,9.0,0.0,0,34,636092489_34,9142,9142,2.966057
122882,2017-02-15 01:04:12,2017-02-13 09:45:41,636092587,-36.7352,-73.1409,4.0,2.0,1,35,636092587_35,1,1968,1.567459
122883,2017-02-23 21:55:05,2017-02-23 21:52:33,636092587,8.9580,-79.5686,1.0,0.0,0,35,636092587_35,1968,1968,0.860275
122890,2016-02-11 01:20:50,2016-02-09 17:59:24,636092592,-20.2044,-70.1556,1.0,2.0,1,9,636092592_9,1,1042,0.628138
122891,2016-02-16 13:31:04,2016-02-16 12:53:48,636092592,-33.5875,-71.6217,1.0,0.0,0,9,636092592_9,1042,1042,0.316338
123026,2017-10-25 05:00:18,2017-10-23 04:34:06,636092793,31.8526,-116.6287,1.0,2.0,1,5,636092793_5,1,3701,1.037358
123027,2017-11-17 11:31:31,2017-11-17 11:16:28,636092793,30.6069,122.0833,2.0,0.0,0,5,636092793_5,3701,3701,1.530590
123042,2018-06-04 13:24:32,2018-06-02 06:38:26,636092835,35.0769,128.7938,1.0,2.0,1,8,636092835_8,1,1732,1.353501
123043,2018-06-29 05:47:57,2018-06-29 05:46:26,636092835,49.2891,-123.0934,1.0,0.0,0,8,636092835_8,1732,1732,3.624170

In [11]:
data3.to_csv('C:/Users/renz/Downloads/new_start.csv', row)

# pacific model

In [10]:
import pandas as pd
import folium
from matplotlib import colors as mcolors

In [11]:
colors = pd.DataFrame(dict(mcolors.BASE_COLORS, **mcolors.CSS4_COLORS)).iloc[0,8:]

In [12]:
colors = colors.drop(['black'])
colors = colors.drop(['azure'])

In [13]:
L = list()
for i in range(data6.shape[0]):
        L.append(colors[int(data6['MMSI2'][i][-1])-1])
data6['color'] = L

In [17]:
m = folium.Map(location=[data6.loc[0,'LAT'], data6.loc[0,'LON2']], zoom_start=1)
for i in range(data6.shape[0]):
    folium.CircleMarker(location=[data6.loc[i,'LAT'], data6.loc[i,'LON2']], color = data6.loc[i,'color'], radius = 0.05).add_to(m)

In [18]:
m.save('C:/Users/renz/Downloads/DATA/image.html')

# 태평양 개별로 보기

In [64]:
list_name = list(map('map{}'.format, range(len(data6['MMSI2'].unique()))))
import folium

In [80]:
for i,j in enumerate(data6['MMSI2'].unique()):
    for k, (m, n) in enumerate(zip(data6[data6['MMSI2']==j]['LAT'], data6[data6['MMSI2']==j]['LON2'])):
        if k == 0: 
            list_name[i] = folium.Map(location=[m, n], zoom_start=1)
        else:
            folium.CircleMarker(location=[m, n], color = 'blue', radius = 0.05).add_to(list_name[i])

In [94]:
for i,j in enumerate(list_name):
    j.save('C:/Users/renz/Downloads/DATA/image/pacific/{}.html'.format('image'+str(i+100)))

# learning

In [357]:
data6 = pd.read_csv("C:/Users/renz/Downloads/DATA/BUSAN_LONBEACH_out.csv")

In [453]:
# del data6['color']
del data6['MMSI']
del data6['LON']
del data6['ETA2']
# data6['ETA'] = data6['ETA'].apply(lambda x:x.replace('-', ''))

In [148]:
import arrow

In [465]:
data6_diff_days = data6.groupby('MMSI2')['ETA'].max().apply(lambda x: arrow.get(x))-data6.groupby('MMSI2')['ETA'].min().apply(lambda x: arrow.get(x))

In [466]:
L=list()
for ix in range(data6.shape[0]):
    for i in data6_diff_days.index:
        if data6.loc[ix, 'MMSI2'] == i:
            L.append(data6_diff_days[i])
            break

In [467]:
data6['days'] = L

In [457]:
data6['ETA'] = data6['ETA'].apply(lambda x: x.replace('-', ''))

In [458]:
data6['days'] = data6['days'].apply(lambda x: str(x)[:2])

In [394]:
import numpy as np
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [459]:
X_train, X_test, y_train, y_test = train_test_split(data6.iloc[:,:8], list(data6['days']), test_size=0.33, random_state=1)

In [460]:
regr = LinearRegression()

In [461]:
regr.fit(X_train, y_train)

ValueError: could not convert string to float: '2016-06-02 09:49:03'

In [ ]:
y_pred = regr.predict(X_test)

In [ ]:
y_sqrt = []
for i,j in zip(y_pred, y_test):
    y_sqrt.append((float(i)-float(j))**2)

In [ ]:
np.sqrt(np.mean(y_sqrt))